% Define GUI
scr = get(0,'ScreenSize');
w   = 400;
h   = 500;

BGC = get(0,'DefaultUicontrolBackgroundColor');

% Main figure
t.fig = figure(...
    'position', [scr(3)/2-w/2 scr(4)/2-h/2 w h],...
    'Color', BGC,...
    'Resize', 'off',...
    'Toolbar', 'none',...
    'Menubar', 'none',...
    'Name', 'LagTrack',...
    'NumberTitle', 'off');

t.menu0 = uimenu(t.fig, 'Label', 'File');

        t.name = uipanel(...
            'parent', t.fig,...
            'units', 'normalized',...
            'position', [.04 .8 .92 .18],...
            'title', 'Name',...
            'BackgroundColor', BGC,...
            'ForegroundColor', [.0 .0 .4],...
            'HighlightColor', [.0 .0 .4],...
            'BorderType', 'line');   
            
            t.nameE = uicontrol(...
                'parent', t.name,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.2 .3 .6 .4],...
                'HorizontalAlignment', 'center',...
                'ForegroundColor', [.2 .2 .2],...
                'BackgroundColor', BGC,...
                'String', 'Input name',...
                'ToolTipString', 'Name given to the input datasets');


        t.extent = uipanel(...
            'parent', t.fig,...
            'units', 'normalized',...
            'position', [.04 .5 .92 .28],...
            'title', 'Extent',...
            'BackgroundColor', BGC,...
            'ForegroundColor', [.0 .0 .4],...
            'HighlightColor', [.0 .0 .4],...
            'BorderType', 'line');  
        
            
            t.extentN = uicontrol(...
                'parent', t.extent,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.3 .725 .4 .24],...
                'HorizontalAlignment', 'center',...
                'ForegroundColor', [.2 .2 .2],...
                'BackgroundColor', BGC,...
                'String', 'Latitude North',...
                'ToolTipString', 'Positive in Northen hemisphere, negative in Southern');
        
            
            t.extentS = uicontrol(...
                'parent', t.extent,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.3 .075 .4 .24],...
                'HorizontalAlignment', 'center',...
                'ForegroundColor', [.2 .2 .2],...
                'BackgroundColor', BGC,...
                'String', 'Latitude South',...
                'ToolTipString', 'Positive in Northen hemisphere, negative in Southern');
        
            
            t.extentW = uicontrol(...
                'parent', t.extent,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.05 .41 .4 .24],...
                'HorizontalAlignment', 'center',...
                'ForegroundColor', [.2 .2 .2],...
                'BackgroundColor', BGC,...
                'String', 'Longitude West',...
                'ToolTipString', 'Positive in Eastern hemisphere, negative in Western');
        
            
            t.extentE = uicontrol(...
                'parent', t.extent,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.55 .41 .4 .24],...
                'HorizontalAlignment', 'center',...
                'ForegroundColor', [.2 .2 .2],...
                'BackgroundColor', BGC,...
                'String', 'Longitude East',...
                'ToolTipString', 'Positive in Eastern hemisphere, negative in Western');
        
        
        
        t.wind = uipanel(...
            'parent', t.fig,...
            'units', 'normalized',...
            'position', [.04 .215 .92 .265],...
            'title', 'Era-Interim',...
            'BackgroundColor', BGC,...
            'ForegroundColor', [.0 .0 .4],...
            'HighlightColor', [.0 .0 .4],...
            'BorderType', 'line');  
        
        t.dem = uipanel(...
            'parent', t.fig,...
            'units', 'normalized',...
            'position', [.04 .025 .92 .17],...
            'title', 'SRTM',...
            'BackgroundColor', BGC,...
            'ForegroundColor', [.0 .0 .4],...
            'HighlightColor', [.0 .0 .4],...
            'BorderType', 'line');  
        
        
            
            t.demR = uicontrol(...
                'parent', t.dem,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.05 .275 .5 .45],...
                'HorizontalAlignment', 'center',...
                'ForegroundColor', [.2 .2 .2],...
                'BackgroundColor', BGC,...
                'String', 'Grid resolution (m)',...
                'ToolTipString', sprintf('Grid resolution after linear interpolation.\nThe original resolution of the SRTM dataset is 90 m'));