function update_table(src, part)

%f = ancestor(src, 'figure');
Tdata = get(findobj(ancestor(src, 'figure'), 'Tag', 'DataTable'), 'Data');

data = {part.part.name, ...
    'true',...
    part.part.diam*1e2,...
    part.part.dens,...
    part.part.flat,...
    part.part.elon,...
    part.rel.x,...
    part.rel.y,...
    part.vent.alt+part.rel.z,...
    datestr(part.date+part.rel.t/3600/24),...
    part.traj.time(end),...
    part.traj.z(end),...
    part.traj.uf(end)
    };

CName = {'Name', 'Plot', 'Diameter (mm)', 'Density', 'Flatness', 'Elongation', 'X offset (m)', 'Y offset (m)', 'Altitude (m)', 'Release', 'Flight Time (s)', 'Landing altitude', 'Terminal velocity'};

if isempty(Tdata)
    Tdata = data;
else
    Tdata(size(Tdata,1)+1,:) = data;
end

set(findobj(ancestor(src, 'figure'), 'Tag', 'DataTable'), 'Data', Tdata);

